.pragma library

var FILE_BG_COLOR_NORMAL = "#00AAAAAA";
var FILE_BG_COLOR_PRESSED = "steelblue";

var VERSION = "1.0" ;
var HOMEPAGE = "http://n9dyfi.github.io/TextEditor"
var COLOR_SCHEME = 18;
var DEFAULT_MARGIN = 16;

var HEADER_DEFAULT_HEIGHT_PORTRAIT = 72;
var HEADER_DEFAULT_TOP_SPACING_PORTRAIT = 15;
var HEADER_DEFAULT_BOTTOM_SPACING_PORTRAIT = 15;

var HEADER_DEFAULT_HEIGHT_LANDSCAPE = 64;
var HEADER_DEFAULT_TOP_SPACING_LANDSCAPE = 9;
var HEADER_DEFAULT_BOTTOM_SPACING_LANDSCAPE = 13;

var FONT_FAMILY = "Nokia Pure Text Light";
var FONT_SIZE_LARGE = 32;
var FONT_SIZE_SMALL = 24;
var FONT_SIZE_TINY = 18;
var FONT_FAMILY_BUTTON = "Nokia Pure Text"
var FONT_SIZE_BUTTON = 20;

var TEXT_AREA_HEIGHT = 60
